// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucbjphixtxlzrslmqmpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjYmpwaGl4dHhsenJzbG1xbXB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NDUyNjgsImV4cCI6MjA3MjUyMTI2OH0._gYA7RNfSTRZNwfLdo23xzoEK2Ugy8ASX3oLUHLELeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});